# -*- coding: utf-8 -*-
"""AI Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLQ4HQsuXkDV8iMNs16ZJQDnOINPQlU0
"""

import pandas as pd

def emotion_intensity(confidence):
    if confidence < 0.4:
        return "Low"
    elif confidence < 0.7:
        return "Medium"
    else:
        return "High"


def infer_mental_state(history_df):
    counts = history_df["Predicted Emotion"].value_counts()

    if counts.get("sad", 0) + counts.get("fear", 0) >= 3:
        return "⚠️ Possible emotional distress detected"
    if counts.get("angry", 0) >= 3:
        return "⚠️ High stress or frustration detected"
    if counts.get("happy", 0) >= 3:
        return "✅ Positive emotional wellbeing"
    return "ℹ️ No dominant mental state detected"


def emotion_trend_data(history_df):
    history_df["Time"] = pd.to_datetime(history_df["Time"])
    return history_df.groupby(
        [pd.Grouper(key="Time", freq="H"), "Predicted Emotion"]
    ).size().unstack(fill_value=0)