# -*- coding: utf-8 -*-
"""AI Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLQ4HQsuXkDV8iMNs16ZJQDnOINPQlU0
"""

# app.py
# Advanced Emotion Detection System
# BSD3513 – Introduction to Artificial Intelligence

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from transformers import pipeline
from datetime import datetime

# ---------------------------
# App Configuration
# ---------------------------
st.set_page_config(
    page_title="Advanced Emotion Detection AI",
    page_icon="🧠",
    layout="wide"
)

st.title("🧠 Advanced Emotion Detection System")
st.write(
    """
    This application detects **human emotions from text** using a
    **Transformer-based Natural Language Processing (NLP) model**.
    It supports **real-time analysis**, **batch processing**,
    and **emotion distribution visualisation**.
    """
)

# ---------------------------
# Load Model
# ---------------------------
@st.cache_resource
def load_emotion_model():
    return pipeline(
        "text-classification",
        model="j-hartmann/emotion-english-distilroberta-base",
        return_all_scores=True
    )

emotion_model = load_emotion_model()

# ---------------------------
# Session History
# ---------------------------
if "history" not in st.session_state:
    st.session_state.history = []

# ---------------------------
# Sidebar Controls
# ---------------------------
st.sidebar.header("⚙️ Model Settings")
top_k = st.sidebar.slider("Top-K emotions to display", 3, 7, 5)
confidence_threshold = st.sidebar.slider(
    "Confidence Threshold",
    min_value=0.0,
    max_value=1.0,
    value=0.20,
    step=0.05
)

mode = st.sidebar.radio(
    "Input Mode",
    ["Single Text Analysis", "Batch CSV Analysis"]
)

# ---------------------------
# Emotion Prediction Function
# ---------------------------
def predict_emotion(text):
    predictions = emotion_model(text)[0]
    df = pd.DataFrame(predictions)
    df = df.sort_values("score", ascending=False)
    return df

# ===========================
# MODE 1: SINGLE TEXT
# ===========================
if mode == "Single Text Analysis":

    st.subheader("✍️ Single Text Emotion Detection")

    user_text = st.text_area(
        "Enter text:",
        placeholder="Example: I feel anxious but hopeful about the future."
    )

    if st.button("Analyze Emotion"):
        if user_text.strip() == "":
            st.warning("Please enter text for analysis.")
        else:
            with st.spinner("Analyzing emotions..."):
                result_df = predict_emotion(user_text)

            filtered_df = result_df[result_df["score"] >= confidence_threshold]
            top_df = filtered_df.head(top_k)

            # Store history
            st.session_state.history.append({
                "timestamp": datetime.now(),
                "text": user_text,
                "top_emotion": top_df.iloc[0]["label"],
                "confidence": top_df.iloc[0]["score"]
            })

            col1, col2 = st.columns(2)

            with col1:
                st.subheader("📊 Emotion Scores")
                st.dataframe(top_df.reset_index(drop=True))

            with col2:
                st.subheader("📈 Emotion Distribution")
                fig, ax = plt.subplots()
                ax.bar(top_df["label"], top_df["score"])
                ax.set_ylabel("Confidence Score")
                ax.set_xlabel("Emotion")
                st.pyplot(fig)

            st.success(
                f"Primary Emotion: **{top_df.iloc[0]['label'].upper()}** "
                f"(Confidence: {top_df.iloc[0]['score']:.2f})"
            )

# ===========================
# MODE 2: BATCH CSV
# ===========================
if mode == "Batch CSV Analysis":

    st.subheader("📁 Batch Emotion Detection (CSV)")

    st.write("Upload a CSV file containing a column named **`text`**.")

    uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

    if uploaded_file:
        df = pd.read_csv(uploaded_file)

        if "text" not in df.columns:
            st.error("CSV must contain a column named 'text'.")
        else:
            with st.spinner("Processing batch emotion detection..."):
                emotions = []
                confidences = []

                for text in df["text"]:
                    result_df = predict_emotion(text)
                    top_emotion = result_df.iloc[0]
                    emotions.append(top_emotion["label"])
                    confidences.append(top_emotion["score"])

                df["predicted_emotion"] = emotions
                df["confidence"] = confidences

            st.subheader("✅ Batch Results")
            st.dataframe(df)

            # Aggregate emotion distribution
            st.subheader("📊 Overall Emotion Distribution")
            emotion_counts = df["predicted_emotion"].value_counts()

            fig, ax = plt.subplots()
            ax.bar(emotion_counts.index, emotion_counts.values)
            ax.set_ylabel("Frequency")
            ax.set_xlabel("Emotion")
            st.pyplot(fig)

# ---------------------------
# Session History Display
# ---------------------------
st.markdown("---")
st.subheader("🕒 Analysis History")

if len(st.session_state.history) > 0:
    history_df = pd.DataFrame(st.session_state.history)
    st.dataframe(history_df)
else:
    st.info("No analysis history yet.")

# ---------------------------
# Footer
# ---------------------------
st.markdown("---")
st.markdown(
    """
    **Course:** BSD3513 – Introduction to Artificial Intelligence
    **AI Technique:** Transformer-based NLP (Emotion Classification)
    **Deployment:** Streamlit Cloud + GitHub
    """
)