# -*- coding: utf-8 -*-
"""AI Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLQ4HQsuXkDV8iMNs16ZJQDnOINPQlU0
"""

import streamlit as st
import pandas as pd
from datetime import datetime

from model_utils import load_model, predict_emotion
from text_utils import clean_text
from analytics_utils import emotion_intensity, infer_mental_state, emotion_trend_data
from styles import load_css

# -------------------------------------------------
st.set_page_config(page_title="Emotion & Mental State AI", layout="wide")
st.markdown(load_css(), unsafe_allow_html=True)

# -------------------------------------------------
@st.cache_resource
def init_model():
    return load_model()

model, vectorizer = init_model()

# -------------------------------------------------
if "history" not in st.session_state:
    st.session_state.history = []

# -------------------------------------------------
st.markdown('<div class="main-title">🎭 Emotion & Mental State Analysis System</div>', unsafe_allow_html=True)

text_input = st.text_area("Enter a sentence", height=120)
analyze = st.button("Analyze Emotion")

# -------------------------------------------------
if analyze:
    if text_input.strip() == "":
        st.error("Please enter text.")
    else:
        cleaned = clean_text(text_input)
        emotion, probs, conf = predict_emotion(cleaned, model, vectorizer)
        intensity = emotion_intensity(conf)

        st.session_state.history.append({
            "Time": datetime.now(),
            "Sentence": text_input,
            "Predicted Emotion": emotion,
            "Confidence": round(conf * 100, 2),
            "Intensity": intensity
        })

        st.success(f"Emotion: **{emotion.upper()}**")
        st.info(f"Confidence: {conf*100:.2f}% | Intensity: {intensity}")

        if conf < 0.5:
            st.warning("Low confidence prediction — mixed emotions possible.")

# -------------------------------------------------
st.markdown("---")
st.markdown("## 📜 Prediction History")

if st.session_state.history:
    df = pd.DataFrame(st.session_state.history)
    st.dataframe(df, use_container_width=True)

    st.markdown("## 📊 Emotion Trends")
    trend_df = emotion_trend_data(df)
    st.line_chart(trend_df)

    st.markdown("## 🧠 Mental State Assessment")
    st.write(infer_mental_state(df))

    st.download_button(
        "Download History",
        df.to_csv(index=False),
        "emotion_history.csv",
        "text/csv"
    )

else:
    st.info("No predictions yet.")

# -------------------------------------------------
st.markdown("---")
st.markdown("""
<div class="footer">
<b>AI Emotion & Mental State Analysis System</b><br>
Built with NLP, TF-IDF, Logistic Regression & Streamlit<br>
Educational use only – not a medical diagnosis
</div>
""", unsafe_allow_html=True)