# -*- coding: utf-8 -*-
"""AI Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLQ4HQsuXkDV8iMNs16ZJQDnOINPQlU0
"""

import pickle
import numpy as np

def load_model():
    with open("emotion_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("emotion_vectorizer.pkl", "rb") as f:
        vectorizer = pickle.load(f)
    return model, vectorizer


def predict_emotion(text, model, vectorizer):
    vector = vectorizer.transform([text])
    prediction = model.predict(vector)[0].lower()
    probabilities = model.predict_proba(vector)[0]
    confidence = float(np.max(probabilities))
    return prediction, probabilities, confidence