# -*- coding: utf-8 -*-
"""AI Group Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLQ4HQsuXkDV8iMNs16ZJQDnOINPQlU0
"""

def load_css():
    return """
    <style>
    .main-title {
        font-size: 3rem;
        font-weight: 900;
        text-align: center;
        background: linear-gradient(90deg, #7C3AED, #2563EB, #06B6D4);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
    .metric-box {
        padding: 1rem;
        background: #F9FAFB;
        border-radius: 10px;
        border: 1px solid #E5E7EB;
        text-align:center;
    }
    .footer {
        text-align:center;
        color:#6B7280;
        font-size:0.9rem;
    }
    </style>
    """